# Generated by Django 4.0.6 on 2022-07-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('other', 'Other'), ('dairy', 'Dairy'), ('soft_drinks', 'Soft Drinks'), ('groceries', 'Groceries')], default='1', max_length=100)),
                ('remainder', models.IntegerField(verbose_name='Remainder')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
